CREATE TABLE IF NOT EXISTS Authors (
    Author_ID INT AUTO_INCREMENT PRIMARY KEY,
    Author_Name VARCHAR(215) NOT NULL
);

CREATE TABLE IF NOT EXISTS Books (
    Book_ID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(130) NOT NULL,
    Author_ID INT,
    Price DOUBLE NOT NULL,
    Publication_Date DATE,
    FOREIGN KEY (Author_ID) REFERENCES Authors(Author_ID)
);

CREATE TABLE IF NOT EXISTS Customers (
    Customer_ID INT AUTO_INCREMENT PRIMARY KEY,
    Customer_Name VARCHAR(215) NOT NULL,
    Email VARCHAR(215) UNIQUE NOT NULL,
    Address TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Orders (
    Order_ID INT AUTO_INCREMENT PRIMARY KEY,
    Customer_ID INT,
    Order_Date DATE,
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

CREATE TABLE IF NOT EXISTS Order_Details (
    OrderDetail_ID INT AUTO_INCREMENT PRIMARY KEY,
    Order_ID INT,
    Book_ID INT,
    Quantity DOUBLE NOT NULL,
    FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID),
    FOREIGN KEY (Book_ID) REFERENCES Books(Book_ID)
);

